# Generated by Django 3.2.4 on 2021-07-03 05:41
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        (
            (
                migrations.AlterField(
                    model_name="testmodel",
                    name="active",
                    field=models.NullBooleanField(default=True),
                )
            )
            if django.VERSION < (2, 1)
            else (
                migrations.AlterField(
                    model_name="testmodel",
                    name="active",
                    field=models.BooleanField(default=True),
                )
            )
        ),
    ]
