# Generated by Django 3.2.4 on 2021-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
