# Generated by Django 3.2.4 on 2021-07-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="age",
            field=models.PositiveIntegerField(default=500),
        ),
    ]
