# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="dob",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
